### ISSUE TITLE
Peer review labb 1

### ISSUE THREAD

**Issue by sk222sw** [mj223dg/RegistrationApplication#8]
Tjabba!

Tycker du gjort ett bra jobb. Det märks att du följt railstutorial mycket, men det är bara bra tror jag, eftersom den går igenom många bra saker.  Tycker du har en bra struktur och gillar att du använder partials i vyerna. Bra att du skapar sträng-variabler för att undvika eventuella string dependencies.

Här är de mindre bra grejerna jag hittade. Några viktiga, men mest petiga om knappar och sånt på själva sidan: 
- Inga instruktioner för hur man får igång det när man klonar/forkar.
- Genom att lägga till /users/:id kan man komma åt vilken användare som helst utan att logga in, inklusive Admin-konton
- Errors och stack trace visas när man försöker nå en sida som inte finns. Det borde fångas upp av en 404. (även när den är i production-mode på heroku)
- När man registrerar sig kommer man till sidan med api-nycklar, där finns en knapp som heter back som tar en till nån slags meny. Knappen borde heta nåt annat
- Inga felmeddelanden när man gör fel i registreringen/api-skapandet/inloggningen
- "Users" i menyn leder ingenstans.
- "Home"-knappen kanske borde heta något annat?
- "Your applications" som admin leder till alla applications, kanske också borde heta nåt annat.
- "Settings" i menyn leder ingenstans
- Listan över en inloggad användares applikationer visar användarnamnet, vilket känns onödigt.
- Inga kommentarer i koden. Mycket är såklart självdokumenterande, men en del grejer kan vara bra att förtydliga, till exempel vad en metod som "currentdev_user" gör för något

**Comment by mj223dg** [comment]
Klar med peer review 1.

Tack för feedbacken! :+1:
